### ISSUE TITLE
Add new emergency alert banner to library

### ISSUE THREAD

**Issue by patphongs** [18F/fec-pattern-library#45]
![35460375-d0565edc-02b1-11e8-9b63-7e145c9641bd](https://user-images.githubusercontent.com/12799132/35600120-3cfb63e8-05fa-11e8-83b3-98302d81c7cc.gif)

We need to add this design pattern to the library

**Comment by jenniferthibault** [comment]
I'm not sure I'd recommend we add this pattern to the pattern library, since it actually breaks outside of our standard message and color patterns purposefully, in order to work on this specific page.

I see this as more of a one-off solution for the homepage than a pattern we'd want to encourage to be reused elsewhere on the site.

Let's discuss! What do you think @JonellaCulmer @patphongs ?

**Comment by patphongs** [comment]
That makes sense @jenniferthibault. I thought that we wanted all design patterns to be within the pattern library, but I can see your point that this is really a one time emergency alert banner that we created for a very specific purpose. So I am fine with just closing this ticket for now. We can resurrect if we decide differently later.
