### ISSUE TITLE
Audit first half of the patterns in the pattern library for accuracy 

### ISSUE THREAD

**Issue by jwchumley** [18F/fec-pattern-library#46]
**What we're after:**
Ensuring that the visual styling of patterns is correct and complete in the pattern library

This is a task focused on improving documentation while other design team members are preparing for and participating in testing during the AZ conference.

Completion:
- [x] Review each component page of the pattern library for:
 - accuracy (priority)
 - completeness (secondary)
- [ ] understand what needs to be done to get each component up to date, at wchich point, this issue can be closed in favor of #47

**Comment by jenniferthibault** [comment]
A few parts of my process on this:
- Look at the components in the existing pattern library site:
  - Compare what's presented in the pattern library to a) the live site; b) the design files; in order to see what is the most up to date, comprehensive, and accurate example of the component
  - Make note of what needs to change in the existing pattern library site to to match the canonical design

I'm keeping notes in this 🔒 [Google Doc](https://docs.google.com/document/d/1LrumX8Iq0Frn1cnRrIltAqLAzRmGXYnTrGMBe_s1x7M/edit?usp=sharing). At this point, it's more of a personal scratch pad, and they probably make sense just to me, but by the end of #47 they should make sense to others.

Individual issues will be filed via #47 for findings that reconcile the differences
Updating or adding missing documentation will happen via #48 

The goal of this issue is to complete the audit of the following existing components:
- [ ] Accordions
- [ ] Banner
- [ ] Breadcrumbs
- [ ] Buttons
- [ ] Callout
- [ ] Card icons
- [ ] Contact items
- [ ] Cycle select
- [ ] Documents
- [ ] Figures
- [ ] Filters
- [ ] Footer
- [ ] Header

**Comment by jenniferthibault** [comment]
Made it through the list in my notes document—Closing this issue in favor of moving to itemizing issues in #47
